bagging_fraction: 0.8
bagging_freq: 4
colsample_bytree: 0.8
feature_fraction: 0.5
feature_fraction_bynode: 0.8
imp_cat: missing
imp_num: median
learning_rate: 0.16000000000000003
max_depth: 7
min_child_samples: 5
min_child_weight: 17
n_estimators: 50
num_leaves: 20
reg_alpha: 0.2
reg_lambda: 0.6000000000000001
subsample: 0.9
subsample_freq: 5
