name: LightGBM Classifier
type:
  _target_: main.lightgmb_mod
  colsample_bytree:
    high: 1.0
    low: 0.6
    step: 0.1
  is_unbalance: true
  learning_rate:
    high: 0.26
    low: 0.01
    step: 0.05
  max_depth:
    high: 10
    low: 1
    step: 1
  min_child_weight:
    high: 20
    low: 1
    step: 1
  n_estimators:
    high: 600
    low: 10
    step: 10
  n_jobs: -1
  objective: binary
  random_state: 123
  subsample:
    high: 1.0
    low: 0.6
    step: 0.1
  num_leaves:
    high: 50
    low: 10
    step: 5
  reg_alpha:
    high: 1.0
    low: 0.0
    step: 0.1
  reg_lambda:
    high: 1.0
    low: 0.0
    step: 0.1
  min_child_samples:
    high: 50
    low: 5
    step: 5
  subsample_freq:
    high: 5
    low: 0
    step: 1
  bagging_fraction:
    high: 1.0
    low: 0.5
    step: 0.1
  bagging_freq:
    high: 5
    low: 1
    step: 1
  feature_fraction:
    high: 1.0
    low: 0.5
    step: 0.1
  feature_fraction_bynode:
    high: 1.0
    low: 0.5
    step: 0.1
