name: LightGBM Classifier
type:
  _target_: main.lightgbm
  learning_rate:
    low: 0.01
    high: 0.3
    step: 0.05
  min_child_weight:
    low: 1
    high: 20
    step: 1
  subsample:
    low: 0.6
    high: 1.0
    step: 0.1
  colsample_bytree:
    low: 0.6
    high: 1.0
    step: 0.1
  objective: 'binary'
  is_unbalance: true
  n_jobs: -1
  random_state: 123
  n_estimators:
    low: 10
    high: 600
    step: 10
  max_depth:
    low: 1
    high: 10
    step: 1
  min_samples_split:
    low: 0.1
    high: 1
    q: 0.1