name: LightGBM Classifier
type:
  _target_: main.lightgbm_mod
  colsample_bytree:
    high: 1.0
    low: 0.6
    q: 0.1
  is_unbalance: true
  learning_rate:
    high: 0.3
    low: 0.01
    q: 0.05
  max_depth:
    high: 10
    low: 1
    step: 1
  min_child_weight:
    high: 20
    low: 1
    step: 1
  min_samples_split:
    high: 1
    low: 0.1
    q: 0.1
  n_estimators:
    high: 600
    low: 10
    step: 10
  n_jobs: -1
  objective: binary
  random_state: 123
  subsample:
    high: 1.0
    low: 0.6
    q: 0.1
