name: logistic_regression
type:
  C:
    high: 100
    low: 0.001
  _target_: main.log_reg
  class_weight: 'balanced'
  fit_intercept:
  - false
  - true
  random_state: 123
  solver:
  - lbfgs
  - sag
