name: Logistic Regression
type:
  C:
    high: 100
    low: 0.001
  _target_: train_model.log_reg
  class_weight:
    0: 158165
    1: 1835
  fit_intercept:
  - false
  - true
  solver:
  - lbfgs
  - sag
