name: Random Forest
type:
  _target_: main.random_forest
  class_weight: ['balanced', 'balanced_subsample']
  max_depth:
    high: 10
    low: 1
    step: 1
  min_samples_leaf:
    high: 20
    low: 1
    step: 1
  min_samples_split:
    high: 1
    low: 0.1
    q: 0.1
  n_estimators:
    high: 600
    low: 10
    step: 10
  n_jobs: -1
  random_state: 123
