name: XGBoost Classifier
type:
  _target_: main.xgboost_mod
  colsample_bytree:
    high: 1.0
    low: 0.6
    step: 0.1
  learning_rate:
    high: 0.3
    low: 0.01
    step: 0.05
  max_depth:
    high: 10
    low: 1
    step: 1
  min_child_weight:
    high: 20
    low: 1
    step: 1
  n_estimators:
    high: 600
    low: 10
    step: 10
  n_jobs: -1
  objective: binary:logitraw
  random_state: 123
  scale_pos_weight: 86.19
  subsample:
    high: 1.0
    low: 0.6
    step: 0.1
