defaults:
  - _self_
  - data/get_Xs_ys: get_data
  - data/reduce_memory_usage: reduce_memory_usage
  - data/class_weight: class_weight
  - feature_selection: feature_selection
  - save_selected_columns: save_selected_columns
  - preprocess/imputing/cat_imputer: cat_imputer
  - preprocess/imputing/num_imputer: num_imputer
n_trials: 4



